### ISSUE TITLE
usage of undefined variable in consume external module chapter

### ISSUE THREAD

**Issue by AdityaVarmaUddaraju** [softchris/golang-book#3]
In the chapter consume external module of online version of the book the code example has an error where the variable sum is used without definition

package main
    
import (
  "fmt"
  "github.com/softchris/math"
)

func main() {
  sum += math.Add(1,2)
  fmt.Println(sum)
}

the line   sum += math.Add(1,2)  should be replaced with sum := math.Add(1,2)

**Comment by softchris** [comment]
Thanks for raising Aditya, are you able to make a PR?
